version: "3.9"

services:

  prolog:
    image: yababay/historian:seeds
    container_name: historical_prolog
    build: ./prolog  
    depends_on: 
      - redis
    volumes:
      - prolog_data:/srv/test
    networks:
      historian-network:
        ipv4_address: 192.168.167.10

  redis:
    image: redis:bullseye
    container_name: historical_redis
    volumes:
      - redis_data:/data
    networks:
      historian-network:
        ipv4_address: 192.168.167.11

volumes:
  redis_data:
    external: false
  prolog_data:
    external: true

networks:
  historian-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.167.0/24
          gateway: 192.168.167.167

